### ISSUE TITLE
Rain drops are large and slow

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#630]
Rain drops are large and slow.

Testable on Skirmish map "Eastern Everglades (4)"

![shot_20220225_220246_1](https://user-images.githubusercontent.com/4720891/155854860-86485b7d-60e6-46b0-9142-c20463658f01.jpg)

**Comment by jonwil** [comment]
Regression testing this now.
Confirmed as not broken in commit 7df49e2463300e40a8b06bc7b7bf1012e60d8a74

**Comment by jonwil** [comment]
Confirmed as not broken in commit 47918425eabb6e61c2719ecba454309bac06b8df

**Comment by jonwil** [comment]
Confirmed as not broken in commit 534d6c21ff842e3f5ba4c689c0b4a71633adbb45

**Comment by jonwil** [comment]
Confirmed as broken in commit 0a796d927900872b127857a1fdd06ef95434416d

**Comment by jonwil** [comment]
Confirmed as not broken in commit b9283512fb605fc19dd5d1e9f5cef0ac19506d6b

**Comment by jonwil** [comment]
Confirmed as broken in commit 3f535c8f3d0c1afb59850871a184d397f9b1be2e

**Comment by jonwil** [comment]
This is broken by commit ca6f77092f7e20e98b8946f73fe42707b054de9a
That commit caused WeatherSetting::Parse_Weather_Definition to be called instead of the stock function.
But WeatherSetting::Parse_Weather_Definition is incomplete (see // TODO requires SnowManager virtual table layout implementing.) which means W3DSnowManager::updateIniSettings/SnowManager::updateIniSettings is never called and that breaks the rain.

Fix is to either implement SnowManager stuff (there is an open PR for that) and fix the todo or return to using the stock version of WeatherSetting::Parse_Weather_Definition for now.

**Comment by jonwil** [comment]
After looking at the SnowManager PR, it seems like switching to the stock version of Parse_Weather_Definition is the better choice right now.
